### ISSUE TITLE
Would you please send me the file a32s.ini in your project arma-to-socket,very thanks.

### ISSUE THREAD

**Issue by yybao** [Tirpitz93/a32s#4]
Dear Tirpitz93,
I have compiled your a32s successful, but when i try to run it，I get one Assertion which tips that we have empty hostandport.  Then I read your code and find this line "std::ifstream settings_file("a32s.ini", std::ifstream::in);" in the file "arma-to-socket.cpp"， I suppose there should be one file "a32s.ini".  While I find noting.  
Would you please send me the file a32s.ini in your project?  or reply the contents of it, i will be very appreciate.
I don't know much more of arma and boost. If i have taken wrong  tracks, please let me know. Thank you very much!

**Comment by Tirpitz93** [comment]
have a look here: https://github.com/Tirpitz93/a32s/wiki/Config-guide
does that help?
I am not currently at my computer, but will look at getting it uploaded tonight.

Also have a look at intercept: https://github.com/intercept/intercept, it is more mature and fully featured than this project. I am myself planning to migrate to intercept soon, then this project will be abondoned, as it has served its purpose.

**Comment by yybao** [comment]
Thank you very much for your reply!It is very helpful to me.Now I have been able to use this plug-in for data transmission.
Now I receive data through this command "s:udp:recv:test",But the result I get is always "0:Invalid argument",So can you give me some answers about how to receive data?Thanks again for the plugin you provided!

**Comment by byjokese** [comment]
> 
> 
> have a look here: https://github.com/Tirpitz93/a32s/wiki/Config-guide
> does that help?
> I am not currently at my computer, but will look at getting it uploaded tonight.
> 
> Also have a look at intercept: https://github.com/intercept/intercept, it is more mature and fully featured than this project. I am myself planning to migrate to intercept soon, then this project will be abondoned, as it has served its purpose.

Did you update something to intercept? Have you manage to do sockets with intercept?

**Comment by Tirpitz93** [comment]
> > have a look here: https://github.com/Tirpitz93/a32s/wiki/Config-guide
> > does that help?
> > I am not currently at my computer, but will look at getting it uploaded tonight.
> > Also have a look at intercept: https://github.com/intercept/intercept, it is more mature and fully featured than this project. I am myself planning to migrate to intercept soon, then this project will be abondoned, as it has served its purpose.
> 
> Did you update something to intercept? Have you manage to do sockets with intercept?

I have done nothing on this project in years.

As with my other projects I have started working on them more and more recently.
